version: '3'

services:

  rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  
  microsservice-a:
    image: almerindo/microservico-avancadev-a:latest
    ports:
      - 9090:9090
  
  microsservice-b:
      image: almerindo/microservico-avancadev-b:latest
      ports:
        - 9091:9091
  
  microsservice-c:
      image: almerindo/microservico-avancadev-c:latest
      ports:
        - 9092:9092
  